# Define the goal
#float32 x
#float32 y
#float32 theta
geometry_msgs/PoseStamped target_pose
---
# Define the result
bool ok
---
# Define a feedback message
#float32 actualx
#float32 actualy
#float32 actualtheta
geometry_msgs/Pose actual_pose
string stat





